# -*- coding: utf-8 -*-
"""my_pythan_threatre.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f6GXg5ZXI9zrhDakvtZQTAhZC7W_RDGs
"""

threatre_capacity = 350
booking_num=0
booking_count=0
booking_fail=0
while threatre_capacity > 0:
  booking_size =int(input("enter how many tickets you can booking"))
  if booking_size > threatre_capacity:
    print("Booking cancelled: Not enough theatre capacity.")
    break
  elif booking_size!=0 and booking_size<=15:
    booking_num +=1
    print(f"Booking number: {booking_num}")
  else:
    print("Booking cancelled: Invalid booking size.")
    continue
  ages = []
  booking_cancelled = False
  print(f"Attempting to book {booking_size} tickets.")
  for i in range(booking_size):
      try:
          age = int(input(f"Enter age for person {i+1}: "))
          if age < 12:
              print("Age less than 12 detected. Booking will be cancelled.")
              booking_fail+=1
              booking_num-=1
              booking_cancelled = True
              break
          ages.append(age)
      except ValueError:
          print("Invalid input. Please enter a number for age. Booking cancelled.")
          booking_fail+=1
          booking_cancelled = True
          break
  if booking_cancelled:
    print("Booking cancelled due to age restrictions or invalid input.")
  else:
      if threatre_capacity >= booking_size and booking_size!=0:
        print("All ages are 12 or older. Proceeding with booking.")
        print(f"Ages booked: {ages}")
        booking_count+=booking_size
        threatre_capacity -= booking_size
        print(f"Booking successful.\n","Total Booking:",f"{booking_num}","Total Number of tickets sold:",booking_count,"\nRejected Booking:",booking_fail,f"\nRemaining theatre capacity: {threatre_capacity}")
      else:
        print("Booking cancelled: Not enough theatre capacity.")
        booking_fail+=1